# Generated by Django 6.0.5 on 2026-06-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_recebimento',
            field=models.CharField(choices=[('entrega', 'Entrega em casa'), ('retirada', 'Retirada na loja')], default='entrega', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('pix_online', 'Pix online'), ('cartao_online', 'Cartão online')], default='dinheiro', max_length=20),
        ),
    ]
