# Generated by Django 6.0.5 on 2026-06-09 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_groups_remove_cliente_is_active_and_more'),
        ('pedidos', '0002_pedido_forma_recebimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='clientes.cliente'),
        ),
    ]
