# Generated by Django 6.0.5 on 2026-06-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_latitude_pedido_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='longitude',
        ),
    ]
