# Generated by Django 6.0.5 on 2026-06-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_pedido_latitude_remove_pedido_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
